name: Terminal GIF

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          pip install git+https://github.com/x0rzavi/github-readme-terminal.git@main

      - name: Generate terminal GIF
        run: python terminal.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIFOS_GENERAL_FPS: 13
          GIFOS_GENERAL_LOOP_COUNT: 0
          GIFOS_GENERAL_COLOR_SCHEME: "catppuccin-mocha"

      - name: Commit
        run: |
          mkdir -p profile
          mv output.gif profile/terminal.gif
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/terminal.gif
          git commit -m "Update terminal GIF" || exit 0
          git push
